Repository INN/umbrella-currentorg, pull requests merged in 2019-07, with the labels that each got.

#53 48 listing page updates
  wp-content/themes/currentorg/business-directory/main-box.tpl.php
  wp-content/themes/currentorg/business-directory/single.tpl.php
  wp-content/themes/currentorg/css/wpbdp.css
  wp-content/themes/currentorg/css/wpbdp.css.map
  wp-content/themes/currentorg/css/wpbdp.min.css
  wp-content/themes/currentorg/inc/business-directory-plugin.php
  wp-content/themes/currentorg/less/wpbdp.less
Labels: in progress

#79 Display 'fee plan' images on submit listing and login pages
  wp-content/themes/currentorg/business-directory/img/basic-fee-plan.png
  wp-content/themes/currentorg/business-directory/img/enhanced-fee-plan.png
  wp-content/themes/currentorg/business-directory/img/leading-fee-plan.png
  wp-content/themes/currentorg/css/wpbdp.css
  wp-content/themes/currentorg/css/wpbdp.css.map
  wp-content/themes/currentorg/css/wpbdp.min.css
  wp-content/themes/currentorg/inc/business-directory-plugin.php
  wp-content/themes/currentorg/less/wpbdp.less
Labels: Estimate < 2 Hours, Priority: High

#83 make sure all images in the bottom of a listing have same alignment.
  wp-content/themes/currentorg/css/wpbdp.css
  wp-content/themes/currentorg/css/wpbdp.css.map
  wp-content/themes/currentorg/css/wpbdp.min.css
  wp-content/themes/currentorg/less/wpbdp.less
Labels: Type: Bug/Issue

#87 Add logo back to above sidebar
  wp-content/themes/currentorg/partials/sidebar-wpbdp-listing-sidebar.php
Labels: Estimate < 2 Hours, Priority: High

#91 Update copy on login and submit listing pages
  wp-content/themes/currentorg/inc/business-directory-plugin.php
Labels: Estimate < 2 Hours

#96 Update global nav bar and don't miss menu font sizes
  wp-content/themes/currentorg/style.css
Labels: Estimate < 2 Hours

#100 Updated spacing and font sizes on Submit Listing page
  wp-content/themes/currentorg/css/wpbdp.css
  wp-content/themes/currentorg/css/wpbdp.css.map
  wp-content/themes/currentorg/css/wpbdp.min.css
  wp-content/themes/currentorg/less/wpbdp.less
Labels: Estimate < 2 Hours

#98 Edit "Submit Listing" form to make user choose plan before categories
  wp-content/themes/currentorg/css/wpbdp.css
  wp-content/themes/currentorg/css/wpbdp.css.map
  wp-content/themes/currentorg/css/wpbdp.min.css
  wp-content/themes/currentorg/inc/business-directory-plugin.php
  wp-content/themes/currentorg/js/business-directory-plugin-submit-listing.js
  wp-content/themes/currentorg/less/wpbdp.less
Labels: Estimate < 6 Hours

#103 Miscellaneous text updates
  wp-content/themes/currentorg/css/wpbdp.css
  wp-content/themes/currentorg/css/wpbdp.css.map
  wp-content/themes/currentorg/css/wpbdp.min.css
  wp-content/themes/currentorg/inc/business-directory-plugin.php
  wp-content/themes/currentorg/js/business-directory-plugin-edit-listing.js
  wp-content/themes/currentorg/js/business-directory-plugin-submit-listing.js
  wp-content/themes/currentorg/less/wpbdp.less
Labels: Estimate < 2 Hours
